name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      fail-fast: false
      matrix:
        otp: ['25.1']
        elixir: [
          '1.13.0',
          '1.13.1',
          '1.13.2',
          '1.13.3',
          '1.13.4',
          '1.14.0',
          '1.14.1'
        ]

    services:
      db:
        image: postgres:latest
        ports: ['5432:5432']
        env:
          POSTGRES_DB: gorilla_dev
          POSTGRES_USER: gorilla
          POSTGRES_PASSWORD: gorilla
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Get dependencies
        run: make deps
        env:
          APP_NAME: Gorilla
          APP_PORT: 4000
          APP_SECRET: 76b3tsME0Sixg04dlGsxx48vhJz5EZndgXTUly32vxpsgifl5J/QDZRfe/zv0WSR
          APP_HOST: localhost
          APP_HTTP_SCHEMA: http
          DB_USERNAME: gorilla
          DB_PASSWORD: gorilla
          DB_HOSTNAME: localhost
          DB_DATABASE: gorilla_dev
          DB_PORT: 5432
          DB_SSL: off
          DB_CA_CERTFILE_PATH:


      - name: Check gorilla format
        run: make fmt_check
        env:
          APP_NAME: Gorilla
          APP_PORT: 4000
          APP_SECRET: 76b3tsME0Sixg04dlGsxx48vhJz5EZndgXTUly32vxpsgifl5J/QDZRfe/zv0WSR
          APP_HOST: localhost
          APP_HTTP_SCHEMA: http
          DB_USERNAME: gorilla
          DB_PASSWORD: gorilla
          DB_HOSTNAME: localhost
          DB_DATABASE: gorilla_dev
          DB_PORT: 5432
          DB_SSL: off
          DB_CA_CERTFILE_PATH:

      - name: Test gorilla
        run: make ci
        env:
          APP_NAME: Gorilla
          APP_PORT: 4000
          APP_SECRET: 76b3tsME0Sixg04dlGsxx48vhJz5EZndgXTUly32vxpsgifl5J/QDZRfe/zv0WSR
          APP_HOST: localhost
          APP_HTTP_SCHEMA: http
          DB_USERNAME: gorilla
          DB_PASSWORD: gorilla
          DB_HOSTNAME: localhost
          DB_DATABASE: gorilla_dev
          DB_PORT: 5432
          DB_SSL: off
          DB_CA_CERTFILE_PATH:

      - name: Build gorilla
        run: make build
        env:
          APP_NAME: Gorilla
          APP_PORT: 4000
          APP_SECRET: 76b3tsME0Sixg04dlGsxx48vhJz5EZndgXTUly32vxpsgifl5J/QDZRfe/zv0WSR
          APP_HOST: localhost
          APP_HTTP_SCHEMA: http
          DB_USERNAME: gorilla
          DB_PASSWORD: gorilla
          DB_HOSTNAME: localhost
          DB_DATABASE: gorilla_dev
          DB_PORT: 5432
          DB_SSL: off
          DB_CA_CERTFILE_PATH:
